import { createRouter, createRootRouteWithContext, RouterProvider } from '@tanstack/react-router';
import { QueryClient } from '@tanstack/react-query';
import { api } from './api/client';
import { useAuth } from './features/auth/authState';

// Define router context type
export interface RouterContext {
  queryClient: QueryClient;
  apiClient: typeof api;
  auth: ReturnType<typeof useAuth>;
}

// Create root route with context
export const rootRoute = createRootRouteWithContext<RouterContext>()({
  component: () => <div />, // This will be replaced by layouts in route definitions
});

// Import route tree (will be generated by routes)
import { routeTree } from './routeTree.gen';

// Router provider component that creates the router with proper context
export function AppRouter() {
  const auth = useAuth();

  const router = createRouter({
    routeTree,
    context: {
      queryClient: new QueryClient({
        defaultOptions: {
          queries: {
            staleTime: 1000 * 60 * 5, // 5 minutes
            gcTime: 1000 * 60 * 10, // 10 minutes
          },
        },
      }),
      apiClient: api,
      auth,
    },
  });

  return <RouterProvider router={router} />;
}

// Router is created dynamically in AppRouter component
// No static router instance available for TypeScript registration
